### ISSUE TITLE
Feature Request: Stats Placeholders

### ISSUE THREAD

**Issue by Swirren** [xMystik/JoltingTrims#1]
This is a great plugin, but there's one big QOL thing I'd like to see: stats on the menu buttons
For example, on the Materials item, it could have a "x/10 unlocked" and a "currently selected: "
Same thing for the Patterns
This is what I would expect it to look like
![image](https://github.com/xMystik/JoltingTrims/assets/64167426/1128ffd0-e04f-4c2b-95e6-aee4cf124733)

**Comment by xMystik** [comment]
The features you requested have been added and can be found on the newer version uploaded on Spigot :)

**Comment by Swirren** [comment]
This is awesome! It does work for the intended spots, but I just want to note that putting these anywhere else doesn't properly show.
![image](https://github.com/xMystik/JoltingTrims/assets/64167426/6b761412-a06f-4e2f-b99e-1f2636f577fe)

**Comment by xMystik** [comment]
Indeed, that's because basically the Unlocked and Maximum Placeholders are referred to their respective item, so on Apply Changes it's not a material nor a pattern item representative, so it does not really make much sense for these to be added there, although if you want to use something similar on the Apply Changes button I could add both selected Material and Pattern as placeholders. In the end, if that's not enough then I could totally just make every placeholder universal to be used on all the items of General GUI.

**Comment by xMystik** [comment]
Actually, I've thought about having a more strict usage of the placeholders to reduce possible misunderstanding and user errors. But now that I think about it I'll probably just make a separate placeholder for each value that can be used in any item of the GUI. Sounds more usable and customizable.
